---
version: "2.1"

services:
    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - kong

    migration:
        image: kong:0.13.0
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=db
        depends_on:
            db:
                condition: service_healthy
        command: kong migrations up
        networks:
            - kong

    kong:
        image: kong:0.13.0
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=db
            - KONG_PG_DATABASE=kong
            - KONG_ADMIN_LISTEN=0.0.0.0:8001
        depends_on:
            db:
                condition: service_healthy
            migration:
                condition: service_started
        ports:
            - 8000
            - 8001:8001
        healthcheck:
            test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
            interval: 5s
            retries: 10
        networks:
            - kong

networks:
    kong:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.32.0.21/24
                  gateway: 172.32.0.21
